// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Link struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Address string `json:"address"`
	User    *User  `json:"user"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewLink struct {
	Title   string `json:"title"`
	Address string `json:"address"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Pair struct {
	ID                  string  `json:"id"`
	Token0              *Token  `json:"token0"`
	Token1              *Token  `json:"token1"`
	Balance0            float64 `json:"balance0"`
	Balance1            float64 `json:"balance1"`
	MarketCap           float64 `json:"marketCap"`
	TotalVolumeRecorded float64 `json:"totalVolumeRecorded"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type SwapTransaction struct {
	ID                string  `json:"id"`
	User              *User   `json:"user"`
	InToken           *Token  `json:"inToken"`
	OutToken          *Token  `json:"outToken"`
	InAmount          float64 `json:"inAmount"`
	OutAmount         float64 `json:"outAmount"`
	VolumeContributed float64 `json:"volumeContributed"`
}

type Token struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	TotalSupply float64 `json:"totalSupply"`
	IconURL     string  `json:"iconURL"`
	Price       float64 `json:"price"`
}

type TokenHourData struct {
	Token      *Token  `json:"token"`
	HourID     int     `json:"hourId"`
	TokenPrice float64 `json:"tokenPrice"`
}

type User struct {
	ID             string `json:"id"`
	Username       string `json:"username"`
	HashedPassword string `json:"hashedPassword"`
}

type UserBalance struct {
	User    *User   `json:"user"`
	Token   *Token  `json:"token"`
	Balance float64 `json:"balance"`
}
